### PR TITLE
Updated Posts and comments

### PR DESCRIPTION
**Pull request by bilguuneo**
Changes Made
- Implemented Post and Comment models with proper relationships inside the intro project 
- Added views for post creation, listing, and detail pages
- Created templates for displaying posts and handling comments
- Implemented comment functionality (add/delete)
- Added tests (to run the tests: python manage.py test intro_proj.tests.test_posts)

### CODE REVIEW

**Review by zubies — CHANGES_REQUESTED** [review]
Please add more documentation. Otherwise looks great!

**Comment by cbollsandiego** [comment]
Yeah I think this looks great Bill, one additional thing would be to replace the '/posts' URL to just be the default '' (blank) URL so that we get sent to that homepage when accessing the website from the start. Your HTML files also look great and we can definitely use these when working on the front end! Your tests are very thorough as well which is awesome.

**Comment by bilguuneo** [comment]
Updated the posts as per Connors recommendation. 
Changes Made
- Integrated posts functionality as the homepage
- Added post creation and comment system
- Implemented admin-only post deletion
- Fixed navigation and cancel button functionality 

Created a super user to test the admin privileges

**Comment by cbollsandiego** [comment]
All the requested changes have been addressed, not sure why Github is still blocking it. Force merging this branch into main as Bill has corrected everything that was mentioned by both reviewers.

**Pull request merged**
